<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.globitel.task.management.system</groupId>
        <artifactId>task-management-system-core</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>task-management-system-core-comment</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>task-management-system-core-comment-entity</module>
        <module>task-management-system-core-comment-identity</module>
        <module>task-management-system-core-comment-dao</module>
        <module>task-management-system-core-comment-usecase</module>
        <module>task-management-system-core-comment-port</module>
        <module>task-management-system-core-comment-factory</module>
        <module>task-management-system-core-comment-jpa</module>
        <module>task-management-system-core-comment-factory-domain</module>
    </modules>


</project>